export const CHANGE_INPUT_VALUE = "CHANGE_INPUT_VALUE";
export const ADD_INPUT_VALUE = "ADD_INPUT_VALUE";
export const DELETE_TODO = "DELETE_TODO";
export const GET_TODO_LIST = "GET_TODO_LIST";
export const INIT_TODO_LIST = "INIT_TODO_LIST";
